# http://www.kaichan.info/blog/2014-02-23-emacs-cask.html
language: emacs-lisp
sudo: false
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
addon:
  apt:
    sources:
      - cassou-emacs
    packages:
      - $EMACS
before_script:
  - $EMACS --version
script: make test emacs=$EMACS
